name: ModelOps (Update Model)
# Requires GitHub Action Secrets: AZURE_STORAGE_CONNECTION_STRING, MONGODB_URI

on:
  workflow_dispatch:

jobs:
  model:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.2'  # Passe an deine Python-Version an
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        working-directory: ./scraper
        run: python scraper.py

      - name: Upload data to MongoDB
        working-directory: ./scraper
        run: python mongo_import.py -c skitour -i ./downloads/skitouren_daten.jl -u "${{ secrets.MONGODB_URI }}"

      - name: Train model
        working-directory: ./model
        run: python model.py -u "${{ secrets.MONGODB_URI }}"

      - name: Save model to Azure Blob
        working-directory: ./model
        run: python save.py -c "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"

